### ISSUE TITLE
文档需要是在线可读

### ISSUE THREAD

**Issue by yue-1998** [sunseekervvv/web#1]
各tasks文档需提交至github，所有需要提交的文档需要是在线可读，建议过用Wiki Pages写。

**Comment by sunseekervvv** [comment]
收到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sunseekervvv/web"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月13日(星期四) 上午9:33
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[sunseekervvv/web] 文档需要是在线可读 (#1)





 
各tasks文档需提交至github，所有需要提交的文档需要是在线可读，建议过用Wiki Pages写。
